# Generated by Django 3.0.9 on 2020-08-10 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0002_auto_20200807_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(default='exit'),
            preserve_default=False,
        ),
    ]
